name: deid_robust
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - allennlp==2.9.0
  - beautifulsoup4==4.10.0
  - datasets==1.18.3
  - huggingface::transformers==4.11.3
  - ipywidgets==7.6.5
  - jupyterlab==3.2.9
  - matplotlib==3.4.3
  - nltk
  - numpy==1.21.2
  - nvidia::cudatoolkit==11.1.1
  - pandas==1.3.3
  - pip
  - python=3.7
  - pytorch::pytorch==1.10.0
  - scikit-learn==1.0.1
  - scipy==1.7.2
  - spacy==3.0.6
  - stanza==1.3.0
  - tensorflow==2.7.0
  - pip:
      - annotated-types==0.5.0
      - conllu==4.5.3
      - en-core-sci-lg==0.4.0
      - en-core-sci-sm==0.4.0
      - jsonlines==3.1.0
      - nmslib==2.1.1
      - nodejs==0.1.1
      - optional-django==0.1.0
      - pip-autoremove==0.10.0
      - pybind11==2.6.1
      - pycorenlp==0.3.0
      - pydantic==1.7.4
      - pydantic-core==2.10.0
      - pysbd==0.3.4
      - robust-deid==0.3.1
      - scispacy==0.4.0
      - seqeval==1.2.2
      - tensorflow-addons==0.15.0
      - typeguard==2.13.3
      - typing-extensions==4.7.1
      - wget==3.2
